name: ambulance_app_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  page_view_dot_indicator: ^2.0.0
  google_maps_flutter: ^2.2.5
  sliding_up_panel: ^2.0.0+1
  pinput: ^2.2.30
  firebase_auth: ^4.2.8
  geocoding: ^2.0.0
  geolocator: ^9.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  location: ^5.0.0
  firebase_core: ^2.7.0
  url_launcher: ^6.1.10
  bloc: ^8.1.1
  intl: ^0.18.1
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  animate_do: ^3.0.2
  equatable: ^2.0.5
  shimmer: ^2.0.0
  mpesadaraja: ^0.1.5
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  path: ^1.8.2
  permission_handler: ^10.2.0
  google_maps_webservice: ^0.0.19
  flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  webview_flutter: ^4.0.7
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/hosy.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "path/to/image.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "path/to/image.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "path/to/image.png"


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/


  fonts:
    - family: Roboto
      fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto-Bold.ttf
         - asset: assets/fonts/Roboto-Italic.ttf
         - asset: assets/fonts/Roboto-Medium.ttf
           style: normal
